apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bf7k
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-bf7k@sha256:facd2673df6b7fdc00cc51b83affe8891dcf8753580faf1604808e83f61c5753
        name: my-nodejs
        resources: {}
status: {}
